from openai import OpenAI , AsyncOpenAI
from dataclasses import dataclass
import json 

# Simple OpenAI API call 
client = OpenAI()

def  askSimple(message: str) -> str:
    response =  client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": message}],
        temperature=0.5,   
    )
    return response.choices[0].message.content


askSimple("What is the capital of France?")



# Calculate cost-aware chat application

class Message:
    def __init__(self, role: str, content: str, tokens: int):
        self.role = role
        self.content = content
        self.tokens = tokens
        
        

# Tool Calling 

# Function Calling: LLMs That Take Action
# ​
# The Pattern
# You define functions the model can “call”
# Model decides which function to call based on user input
# You execute the function and return results
# Model uses results to form final response

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_horoscope",
        "description": "Get today's horoscope for an astrological sign.",
        "parameters": {
            "type": "object",
            "properties": {
                "sign": {
                    "type": "string",
                    "description": "An astrological sign like Taurus or Aquarius",
                },
            },
            "required": ["sign"],
        },
    },
]

def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."

# Create a running input list we will add to over time
input_list = [
    {"role": "user", "content": "What is my horoscope? I am an Aquarius."}
]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model="gpt-5",
    tools=tools,
    input=input_list,
)

# Save function call outputs for subsequent requests
input_list += response.output

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_horoscope":
            # 3. Execute the function logic for get_horoscope
            sign = json.loads(item.arguments)["sign"]
            horoscope = get_horoscope(sign)
            
            # 4. Provide function call results to the model
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": horoscope,
            })

print("Final input:")
print(input_list)

response = client.responses.create(
    model="gpt-5",
    instructions="Respond only with a horoscope generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)



# Async call 
import asyncio

client = AsyncOpenAI()

async def main():
    response = await client.responses.create(
        model="gpt-4.1",
        input="Explain async in python"
    )
    print(response.output[0].content[0].text)

asyncio.run(main())